const Task = require('../models/tasksmodel');

//req.user_id given from auth.js which is gathered from the token jwt
const tasksController = {
	//get all tasks from todo list - access the id
	getTasks: async (req, res) => {
		try {
			const tasks = await Task.find({ user_id: req.user.id });
			res.json(tasks);
		} catch (err) {
			return res.status(500).json({ msg: 'problem with getTasks' });
		}
	},

	//to create pne task - add title and date, user_id would be generated by mongodb
	createOneTask: async (req, res) => {
		try {
			// console.log(req.user.id)
			const { title, date } = req.body;
			// console.log(req.body)
			const newTask = new Task({
				title,
				date,
				user_id: req.user.id,
			});
			await newTask.save();
			// console.log(newTask.id)
			res.json({ msg: 'created new task' });
		} catch (err) {
			return res.status(500).json({ msg: 'problem with createOnetask' });
		}
	},

	//to delete task - access it by task id
	deleteTask: async (req, res) => {
		try {
			await Task.findByIdAndDelete(req.params.id);
			res.json({ msg: 'deleted task' });
		} catch (err) {
			return res.status(500).json({ msg: 'problem with delete one task' });
		}
	},

	//to update task - find it by task id
	updateTask: async (req, res) => {
		try {
			const { title, date } = req.body;
			await Task.findByIdAndUpdate({ _id: req.params.id }, { title, date });
			res.json({ msg: 'updated task' });
		} catch (err) {
			return res.status(500).json({ msg: 'problem with updateTask' });
		}
	},
};

module.exports = tasksController;
